spring:
  main:
    banner-mode: off
  application:
    name: 'accounts-management-service'
  config:
    import: 'optional:configserver:http://localhost:8888'
  datasource:
    driver-class-name: com.google.cloud.spanner.jdbc.JdbcDriver
    url: 'jdbc:cloudspanner:/projects/starry-polymer-365212/instances/spendly-db/databases/liquibase'
  jpa:
    database-platform: 'com.google.cloud.spanner.hibernate.SpannerDialect'
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: 'classpath:db/changelog/db-changelog-master.xml'
springdoc:
  swagger-ui:
    path: '/swagger'
server:
  port: 8100