spring:
  main:
    banner-mode: "off"
  application:
    name: "currency-exchange-service"
  config:
    import: "optional:configserver:http://localhost:8888"
  datasource:
    driver-class-name: org.postgresql.Driver
    url: 'jdbc:postgresql://localhost/spendly'
    username: 'system'
    password: 'system'
  jpa:
      database: postgresql
      database-platform: 'org.hibernate.dialect.PostgreSQLDialect'
      hibernate:
        ddl-auto: update
server:
  port: 8000